# Generated by Django 4.0.4 on 2022-04-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_auto_20220426_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255),
        ),
        migrations.AlterField(
            model_name='user1',
            name='hobby',
            field=models.CharField(choices=[('reading', 'Reading'), ('dance', 'Dance'), ('drawing', 'Drawing')], default='dance', max_length=255),
        ),
        migrations.AlterField(
            model_name='user1',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(default='jinal', max_length=70),
        ),
    ]
