# Generated by Django 4.0.4 on 2022-04-27 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_alter_user_gender_alter_user_id_alter_user1_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user1',
            name='name',
            field=models.CharField(max_length=70),
        ),
    ]
